//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="TahdeerSoap")]
public interface TahdeerSoap
{
    
    // CODEGEN: Generating message contract since message getFinincialIDRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFinincialID", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getFinincialIDResponse getFinincialID(getFinincialIDRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFinincialID", ReplyAction="*")]
    System.Threading.Tasks.Task<getFinincialIDResponse> getFinincialIDAsync(getFinincialIDRequest request);
    
    // CODEGEN: Generating message contract since message getallDeptEMPRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getallDeptEMP", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getallDeptEMPResponse getallDeptEMP(getallDeptEMPRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getallDeptEMP", ReplyAction="*")]
    System.Threading.Tasks.Task<getallDeptEMPResponse> getallDeptEMPAsync(getallDeptEMPRequest request);
    
    // CODEGEN: Generating message contract since message getallDeptInstEMPRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getallDeptInstEMP", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getallDeptInstEMPResponse getallDeptInstEMP(getallDeptInstEMPRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getallDeptInstEMP", ReplyAction="*")]
    System.Threading.Tasks.Task<getallDeptInstEMPResponse> getallDeptInstEMPAsync(getallDeptInstEMPRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class UserCredentials
{
    
    private string userNameField;
    
    private string passwordField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string userName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFinincialID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getFinincialIDRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public UserCredentials UserCredentials;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string FinancialID;
    
    public getFinincialIDRequest()
    {
    }
    
    public getFinincialIDRequest(UserCredentials UserCredentials, string FinancialID)
    {
        this.UserCredentials = UserCredentials;
        this.FinancialID = FinancialID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFinincialIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getFinincialIDResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataTable getFinincialIDResult;
    
    public getFinincialIDResponse()
    {
    }
    
    public getFinincialIDResponse(System.Data.DataTable getFinincialIDResult)
    {
        this.getFinincialIDResult = getFinincialIDResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getallDeptEMP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getallDeptEMPRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public UserCredentials UserCredentials;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int PageNo;
    
    public getallDeptEMPRequest()
    {
    }
    
    public getallDeptEMPRequest(UserCredentials UserCredentials, int PageNo)
    {
        this.UserCredentials = UserCredentials;
        this.PageNo = PageNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getallDeptEMPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getallDeptEMPResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataTable getallDeptEMPResult;
    
    public getallDeptEMPResponse()
    {
    }
    
    public getallDeptEMPResponse(System.Data.DataTable getallDeptEMPResult)
    {
        this.getallDeptEMPResult = getallDeptEMPResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getallDeptInstEMP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getallDeptInstEMPRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public UserCredentials UserCredentials;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int PageNo;
    
    public getallDeptInstEMPRequest()
    {
    }
    
    public getallDeptInstEMPRequest(UserCredentials UserCredentials, int PageNo)
    {
        this.UserCredentials = UserCredentials;
        this.PageNo = PageNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getallDeptInstEMPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class getallDeptInstEMPResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataTable getallDeptInstEMPResult;
    
    public getallDeptInstEMPResponse()
    {
    }
    
    public getallDeptInstEMPResponse(System.Data.DataTable getallDeptInstEMPResult)
    {
        this.getallDeptInstEMPResult = getallDeptInstEMPResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface TahdeerSoapChannel : TahdeerSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TahdeerSoapClient : System.ServiceModel.ClientBase<TahdeerSoap>, TahdeerSoap
{
    
    public TahdeerSoapClient()
    {
    }
    
    public TahdeerSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TahdeerSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TahdeerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TahdeerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getFinincialIDResponse TahdeerSoap.getFinincialID(getFinincialIDRequest request)
    {
        return base.Channel.getFinincialID(request);
    }
    
    public System.Data.DataTable getFinincialID(UserCredentials UserCredentials, string FinancialID)
    {
        getFinincialIDRequest inValue = new getFinincialIDRequest();
        inValue.UserCredentials = UserCredentials;
        inValue.FinancialID = FinancialID;
        getFinincialIDResponse retVal = ((TahdeerSoap)(this)).getFinincialID(inValue);
        return retVal.getFinincialIDResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getFinincialIDResponse> TahdeerSoap.getFinincialIDAsync(getFinincialIDRequest request)
    {
        return base.Channel.getFinincialIDAsync(request);
    }
    
    public System.Threading.Tasks.Task<getFinincialIDResponse> getFinincialIDAsync(UserCredentials UserCredentials, string FinancialID)
    {
        getFinincialIDRequest inValue = new getFinincialIDRequest();
        inValue.UserCredentials = UserCredentials;
        inValue.FinancialID = FinancialID;
        return ((TahdeerSoap)(this)).getFinincialIDAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getallDeptEMPResponse TahdeerSoap.getallDeptEMP(getallDeptEMPRequest request)
    {
        return base.Channel.getallDeptEMP(request);
    }
    
    public System.Data.DataTable getallDeptEMP(UserCredentials UserCredentials, int PageNo)
    {
        getallDeptEMPRequest inValue = new getallDeptEMPRequest();
        inValue.UserCredentials = UserCredentials;
        inValue.PageNo = PageNo;
        getallDeptEMPResponse retVal = ((TahdeerSoap)(this)).getallDeptEMP(inValue);
        return retVal.getallDeptEMPResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getallDeptEMPResponse> TahdeerSoap.getallDeptEMPAsync(getallDeptEMPRequest request)
    {
        return base.Channel.getallDeptEMPAsync(request);
    }
    
    public System.Threading.Tasks.Task<getallDeptEMPResponse> getallDeptEMPAsync(UserCredentials UserCredentials, int PageNo)
    {
        getallDeptEMPRequest inValue = new getallDeptEMPRequest();
        inValue.UserCredentials = UserCredentials;
        inValue.PageNo = PageNo;
        return ((TahdeerSoap)(this)).getallDeptEMPAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getallDeptInstEMPResponse TahdeerSoap.getallDeptInstEMP(getallDeptInstEMPRequest request)
    {
        return base.Channel.getallDeptInstEMP(request);
    }
    
    public System.Data.DataTable getallDeptInstEMP(UserCredentials UserCredentials, int PageNo)
    {
        getallDeptInstEMPRequest inValue = new getallDeptInstEMPRequest();
        inValue.UserCredentials = UserCredentials;
        inValue.PageNo = PageNo;
        getallDeptInstEMPResponse retVal = ((TahdeerSoap)(this)).getallDeptInstEMP(inValue);
        return retVal.getallDeptInstEMPResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getallDeptInstEMPResponse> TahdeerSoap.getallDeptInstEMPAsync(getallDeptInstEMPRequest request)
    {
        return base.Channel.getallDeptInstEMPAsync(request);
    }
    
    public System.Threading.Tasks.Task<getallDeptInstEMPResponse> getallDeptInstEMPAsync(UserCredentials UserCredentials, int PageNo)
    {
        getallDeptInstEMPRequest inValue = new getallDeptInstEMPRequest();
        inValue.UserCredentials = UserCredentials;
        inValue.PageNo = PageNo;
        return ((TahdeerSoap)(this)).getallDeptInstEMPAsync(inValue);
    }
}
